//3_1
SELECT * FROM DEPT WHERE lower(DEPTADDR) IN ('new york','chicago')

SELECT min(SALVALUE) FROM SALARY WHERE YEAR=2009

SELECT * FROM EMP WHERE BIRTHDATE >= to_date('1-01-1960', 'dd-mm-yyyy')

SELECT count(*) FROM EMP

SELECT lower(EMPNAME) FROM EMP WHERE EMPNAME NOT LIKE '% %'

SELECT CASE WHEN substr(lower(empname),-1) = 't'  THEN
                substr(lower(empname),0, length(lower(empname))-1)
ELSE 
      lower(EMPNAME)
END as name
FROM EMP WHERE EMPNAME NOT LIKE '% %'

SELECT TO_CHAR(BIRTHDATE, 'DD-MONTH-YEAR') AS BIRTH_DATE FROM EMP;

SELECT TO_CHAR(BIRTHDATE, 'DD-MONTH-YYYY') AS BIRTH_DATE FROM EMP;

SELECT (CASE WHEN jobname IN ('DRIVER', 'CLERK') 
      THEN 'WORKER'
ELSE 
      jobname 
END) AS jobnam
FROM JOB;

SELECT YEAR, AVG(SALVALUE) FROM SALARY GROUP BY YEAR HAVING COUNT(MONTH) >= 3

SELECT EMP.EMPNAME, SALARY.MONTH, SALARY.SALVALUE FROM SALARY SALARY, EMP EMP WHERE SALARY.EMPNO = EMP.EMPNO;

SELECT EMP.EMPNAME, JOB.JOBNAME, SALARY.SALVALUE, JOB.MINSALARY
			FROM SALARY, EMP, CAREER, JOB
			WHERE SALARY.EMPNO = EMP.EMPNO
			AND CAREER.EMPNO = EMP.EMPNO
			AND JOB.JOBNO = CAREER.JOBNO
			AND SALARY.SALVALUE > JOB.MINSALARY 
			AND SALARY.SALVALUE < JOB.MINSALARY + 500;